### ISSUE TITLE
JSON syntax error on API POST call

### ISSUE THREAD

**Issue by v4rakh** [workflow-editor/worked#3]
On API persist in UI console:

```
SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
```

Maybe related to recent updates done to the project.

Initially reported by @StevNash1337

**Comment by v4rakh** [comment]
@StevNash1337 Could you please provide the `json` from the to be saved workflow? I'm not able to reproduce.

**Comment by StevNash1337** [comment]
This is the `json` output from the file:

`{"id":"299216b5-027f-433c-8f54-c10c30aceaf1","name":"DemoWF","remoteId":null,"mode":"apachecamel","offsetX":0,"offsetY":0,"zoom":100,"links":[{"id":"3547f5cd-6ecd-4312-a3f2-4471c07f76fa","_class":"LinkModel","selected":false,"type":"default","source":"8c19b13a-28f2-4f4c-bdc6-3382734e55cc","sourcePort":"548192f2-609b-4ea1-9abb-fd367092ffff","target":"e81cfbf2-df70-44da-b730-cd4b91b55f07","targetPort":"c706acfa-33f7-44fc-b801-b30a14fc37c9","points":[{"id":"395c194a-899e-44df-8655-fdc1e71270be","_class":"PointModel","selected":false,"x":212.04998779296875,"y":169.5},{"id":"71fde87f-a9d9-4368-9db3-df3d6f5f4ec2","_class":"PointModel","selected":false,"x":294.5,"y":172}],"extras":{}},{"id":"e694af9f-b745-4959-8d4c-ce52561bcff0","_class":"LinkModel","selected":false,"type":"default","source":"e81cfbf2-df70-44da-b730-cd4b91b55f07","sourcePort":"199fcdd3-7308-4f40-ae34-b86e158372de","target":"7edf3ed5-e61c-41eb-ab38-40608bfb866f","targetPort":"5ab7cfd1-d9ff-44ec-bf8b-318f88dbb314","points":[{"id":"460eeced-3b2a-4ed3-8a6a-f26074c45273","_class":"PointModel","selected":false,"x":363.0999755859375,"y":172},{"id":"d0c269e0-984e-40c7-b5a9-450c0b72a539","_class":"PointModel","selected":false,"x":510.5,"y":157}],"extras":{}},{"id":"9c647d2f-6f6e-4c70-aaf9-646b9eb0ee0f","_class":"LinkModel","selected":false,"type":"default","source":"7edf3ed5-e61c-41eb-ab38-40608bfb866f","sourcePort":"bd7b4043-c2a3-4000-9ca0-6d2eb1cc404c","target":"73bab162-de90-4898-b2cd-1e99a7e21bdd","targetPort":"167cbeb9-0a56-4bb1-b8b3-b68e32ba2f13","points":[{"id":"37b93e76-1c4e-4f2e-aef4-4794be5dd2fb","_class":"PointModel","selected":false,"x":579.0999755859375,"y":157},{"id":"ac94f6bd-5cbf-46a6-8fe0-b6b108ca1004","_class":"PointModel","selected":false,"x":818.5,"y":172}],"extras":{}}],"nodes":[{"id":"8c19b13a-28f2-4f4c-bdc6-3382734e55cc","_class":"StartNodeModel","selected":false,"type":"start","x":172.99998474121094,"y":136,"extras":{},"ports":[{"id":"548192f2-609b-4ea1-9abb-fd367092ffff","_class":"DiagramPortModel","selected":false,"name":"out0","parentNode":"8c19b13a-28f2-4f4c-bdc6-3382734e55cc","links":["3547f5cd-6ecd-4312-a3f2-4471c07f76fa"],"in":false,"label":"out0","deletable":true,"multipleConnections":false}],"requiresUpdate":false,"requiresDelete":false,"name":"Start","color":"rgb(0,153,0)"},{"id":"73bab162-de90-4898-b2cd-1e99a7e21bdd","_class":"EndNodeModel","selected":false,"type":"end","x":808.9999847412109,"y":138.5,"extras":{},"ports":[{"id":"167cbeb9-0a56-4bb1-b8b3-b68e32ba2f13","_class":"DiagramPortModel","selected":false,"name":"in0","parentNode":"73bab162-de90-4898-b2cd-1e99a7e21bdd","links":["9c647d2f-6f6e-4c70-aaf9-646b9eb0ee0f"],"in":true,"label":"in0","deletable":true,"multipleConnections":false}],"requiresUpdate":false,"requiresDelete":false,"name":"End","color":"rgb(96,96,96)"},{"id":"e81cfbf2-df70-44da-b730-cd4b91b55f07","_class":"TaskServiceNodeModel","selected":false,"type":"task","x":284.99998474121094,"y":138.5,"extras":{},"ports":[{"id":"c706acfa-33f7-44fc-b801-b30a14fc37c9","_class":"DiagramPortModel","selected":false,"name":"in0","parentNode":"e81cfbf2-df70-44da-b730-cd4b91b55f07","links":["3547f5cd-6ecd-4312-a3f2-4471c07f76fa"],"in":true,"label":"in0","deletable":true,"multipleConnections":false},{"id":"199fcdd3-7308-4f40-ae34-b86e158372de","_class":"DiagramPortModel","selected":false,"name":"out1","parentNode":"e81cfbf2-df70-44da-b730-cd4b91b55f07","links":["e694af9f-b745-4959-8d4c-ce52561bcff0"],"in":false,"label":"out1","deletable":true,"multipleConnections":false}],"requiresUpdate":false,"requiresDelete":false,"name":"Task : service","color":"rgb(255,140,0)","category":"service","path":{"dsl":[{"key":"path","label":"Path","type":"text","value":"","hint":"Set DSL specific path","options":[],"modeId":"path"}],"apachecamel":[{"key":"type","label":"type","type":"select","value":"from","hint":"Type of the service","options":["to","from","toD"],"modeId":"type"},{"key":"uri","label":"uri","type":"text","value":"","hint":"Set an URI for the service call (e.g. mock:result, direct:a, queue:b)","options":[],"modeId":"uri"}]}},{"id":"7edf3ed5-e61c-41eb-ab38-40608bfb866f","_class":"TaskOutputNodeModel","selected":false,"type":"task","x":500.99998474121094,"y":123.5,"extras":{},"ports":[{"id":"5ab7cfd1-d9ff-44ec-bf8b-318f88dbb314","_class":"DiagramPortModel","selected":false,"name":"in0","parentNode":"7edf3ed5-e61c-41eb-ab38-40608bfb866f","links":["e694af9f-b745-4959-8d4c-ce52561bcff0"],"in":true,"label":"in0","deletable":true,"multipleConnections":false},{"id":"bd7b4043-c2a3-4000-9ca0-6d2eb1cc404c","_class":"DiagramPortModel","selected":false,"name":"out1","parentNode":"7edf3ed5-e61c-41eb-ab38-40608bfb866f","links":["9c647d2f-6f6e-4c70-aaf9-646b9eb0ee0f"],"in":false,"label":"out1","deletable":true,"multipleConnections":false}],"requiresUpdate":false,"requiresDelete":false,"name":"Task : output","color":"rgb(255,99,71)","category":"output","path":{"dsl":[{"key":"path","label":"Path","type":"text","value":"","hint":"Set DSL specific path","options":[],"modeId":"path"}],"apachecamel":[{"key":"message","label":"message","type":"text","value":"test message","hint":"Sets the log message (uses simple language)","options":[],"modeId":"message"},{"key":"loggingLevel","label":"loggingLevel","type":"text","value":"INFO","hint":"Sets the logging level. The default value is INFO","options":[],"modeId":"loggingLevel"},{"key":"logName","label":"logName","type":"text","value":"","hint":"Sets the name of the logger","options":[],"modeId":"logName"},{"key":"marker","label":"marker","type":"text","value":"","hint":"To use slf4j marker","options":[],"modeId":"marker"},{"key":"loggerRef","label":"loggerRef","type":"text","value":"","hint":"To refer to a custom logger instance to lookup from the registry.","options":[],"modeId":"loggerRef"}]}}]}`

And this is the error in console:
![error](https://user-images.githubusercontent.com/16450971/69826976-bfd14e80-1215-11ea-9a99-3dd846da1b56.PNG)

I'm using FireFox v. 70.0.1 and the latest repo commit for building the container.

**Comment by v4rakh** [comment]
Unfortunately Firefox is and will not be supported. This is also stated in the about modal.

Basically two reasons for that:

* Focus on _one_ browser
* Weird behavior regarding shortcuts

Maybe the `README.md` needs to be more precise here.

I'll close this ticket. If you like to investigate further and maybe fix this (and the shortcuts), feel free to submit a PR.

**Comment by v4rakh** [comment]
Seems to be related to building the docker image. @StevNash1337 feel free to submit a PR fixing this.

**Comment by StevNash1337** [comment]
#5

**Comment by v4rakh** [comment]
This is just related to the build command and more documentation than a problem with the code itself?
